---
- name: Build image and with build args
  hosts: server
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Set Python 3 interpreter

  tasks:
    - name: install pip
      apt:
        name: python3-pip  # Install pip for Python 3
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        executable: pip3
        state: present
    - name: Build osquery image
      docker_image:
        path: /tmp/path/
        name: imagename
        tag: v1

    # - name: build the image
    #   docker_image: >
    #     command: docker build -t built-by-ansible:ex2 /tmp/site
        # name=built-by-ansible
        # tag=ex1
        # path=/tmp/site
        # state=present

    # - name: build container image
    #   community.docker.docker_image_build:
    #     name: ansible:latest
    #     path: /dockerimage
    #     dockerfile: Dockerfile
