---
- name: Build image and with build args
  hosts: server
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Set Python 3 interpreter

  tasks:
    - name: Install pip
      apt:
        name: python3-pip  # Install pip for Python 3
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        executable: pip3
        state: present

    - name: Build node image
      community.docker.docker_image_build:
        name: ansible:latest
        path: /opt/etc/docker
        dockerfile: Dockerfile-3.12
