---
- name: Build image and with build args
  hosts: server
  become: True
  tasks:
    - name: install pip
      apt:
        name: python-pip
      vars:
        ansible_python_interpreter: /usr/bin/python
    - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: /dockerImage
        state: present

