---
- name: Build image and with build args
  hosts: server
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Set Python 3 interpreter

  tasks:
    - name: install python dependencies
      apt:
        name: python3-pip 
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        executable: pip3
        state: present

    - name: Uninstall Certbot and certbot-nginx
      pip:
        name:
          - certbot
          - certbot-nginx
        state: absent

    - name: Install Certbot and certbot-nginx
      pip:
        name:
          - certbot
          - certbot-nginx
            
    - name: Docker-compose up
      docker_compose:
        project_src: /opt/dockerImage
        files:
        - docker-compose.yml

