---
- name: Build image and with build args
  hosts: server
  become: True
  tasks:
    - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: /root/demo-dockerfile
          source: build
        state: present












# ---
#   - name: Run using a project directory
#     hosts: server
#     gather_facts: no
#     tasks:
#       - name: Tear down existing services
#         docker_compose:
#           project_src: flask
#           state: absent

#       - name: Create and start services
#         docker_compose:
#           project_src: flask
#         register: output

#       - debug:
#           var: output

#       - name: Run `docker-compose up` again
#         docker_compose:
#           project_src: flask
#           build: no
#         register: output

#       - debug:
#           var: output

#       - assert:
#           that: "not output.changed "