---
- name: Build image and with build args
  hosts: server
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Set Python 3 interpreter

  tasks:
    - name: install pip
      apt:
        name: python3-pip  # Install pip for Python 3
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        executable: pip3
        state: present

    - name: build container image
      docker_image:
        name: democontainer:v1.0
        path: ./Dockerfile  # Path to the directory containing Dockerfile and build context
        state: present
