---
- name: Build image and with build args
  hosts: server
  become: True
  tasks:
    - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: /dockerImage
        state: present

