---
- name: Build image and with build args
  hosts: server
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Set Python 3 interpreter

  tasks:
    - name: install pip
      apt:
        name: python3-pip  # Install pip for Python 3
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        executable: pip3
        state: present

    # - name: Debug message
    #   debug:
    #     msg: "Removing Certbot repository"
    # - name: Add Certbot repository
    #   apt_repository:
    #     repo: 'ppa:certbot/certbot'
    #     state: present  # Use 'absent' to remove the repository
    #   become: yes

    # - apt:
    #     name: "{{ item }}"
    #     update_cache: yes
    #   with_items:
    #     - nginx
    #     - python-certbox-nginx
            
    - name: Docker-compose up
      docker_compose:
        project_src: /opt/dockerImage
        files:
        - docker-compose.yml

    - name: Log into ECR registry
      docker_login:
        registry_url: "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 411571901235.dkr.ecr.ap-south-1.amazonaws.com"
        debug: yes
        username: "codecommit+1-at-411571901235"
        password: "buBjN7JaHkWmoYprzhhLAwWJQCc7kMQ55FvxpuNJG+A="
        reauthorize: yes
