apiVersion: latest
kind: Pod
metadata:
  name: mywebapp1
  labels:
    role: webserver-role
    app: nginx
spec:
  containers:
  - name: welcome_docker
    image: 482088842115.dkr.ecr.ap-south-1.amazonaws.com/welcome_cantainer:latest
    ports:
    - containerPort: 8000
